/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <group1_asuforia_NativeCallMethods.h>
#include <opencv2/opencv.hpp>

#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "sampleMSRS", __VA_ARGS__)



using namespace cv;
using namespace std;

JNIEXPORT jstring JNICALL Java_group1_asuforia_NativeCallMethods_getHelloNative
  (JNIEnv *, jclass){

    return jstring("");
}

