/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class group1_asuforia_NativeCallMethods */

#ifndef _Included_group1_asuforia_NativeCallMethods
#define _Included_group1_asuforia_NativeCallMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     group1_asuforia_NativeCallMethods
 * Method:    getHelloNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_group1_asuforia_NativeCallMethods_getHelloNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
