/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class group1_poseestimationmsa_NativeDraw */

#ifndef _Included_group1_poseestimationmsa_NativeDraw
#define _Included_group1_poseestimationmsa_NativeDraw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     group1_poseestimationmsa_NativeDraw
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_group1_poseestimationmsa_NativeDraw_getHello
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_group1_poseestimationmsa_NativeDraw_drawNative(JNIEnv *env, jclass type, jint width,
                                                    jint height, jobject buffer, jobject surface);

JNIEXPORT void JNICALL
Java_group1_poseestimationmsa_NativeDraw_drawNativePose(JNIEnv *env, jclass type, jint width,
                                                        jint height, jobject buffer,
                                                        jobject surface, jfloatArray rvec_,
                                                        jfloatArray tvec_);

#ifdef __cplusplus
}
#endif
#endif
